spring.application.name=provider-service
server.port=8080
logging.level.org.zalando.logbook.Logbook=TRACE
logbook.format.style=http
logbook.strategy=default
logbook.write.max-body-size=-1
logbook.filters.body.default-enabled=false
