spring.application.name=client-service
server.port=8081
provider.soap.uri=http://localhost:8080/ws
logging.level.org.zalando.logbook.Logbook=TRACE
logbook.format.style=http
logbook.strategy=default
logbook.write.max-body-size=-1
logbook.filters.body.default-enabled=false
